title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Tay Kim
github_username: TayKimmy
github_repo: "CSA-Portfolio-2.0"
baseurl: "/CSA-Portfolio-2.0"
# remote_theme: jekyll/minima
remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
